version: "3"

services:

  ipt_connect:
    build: .
    restart: always
    container_name: ipt_connect

    volumes:
      - ./ipt_connect:/ipt_connect
      - static_data:/var/www/ipt_connect/static
      - media_data:/var/www/ipt_connect/media

    environment:
      - WORKERS=3
      - DEV=false


  nginx:
    image: umputun/nginx-le:latest
    hostname: nginx
    restart: always
    container_name: ipt_connect-nginx

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    volumes:
      - ./etc/service.conf:/etc/nginx/service.conf
      - ./ipt_connect:/ipt_connect
      - static_data:/var/www/ipt_connect/static
      - media_data:/var/www/ipt_connect/media

    ports:
      - "80:80"

    environment:
      - TZ=America/Sao_Paulo
      - LE_EMAIL=thiago@saturno.app
      - LE_FQDN=bptnet.info

volumes:
  static_data:
  media_data:
